<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <SupportedOSPlatformVersion>26.0</SupportedOSPlatformVersion>
    <ApplicationId>ir.shadowtrace.game</ApplicationId>
    <ApplicationTitle>رد من</ApplicationTitle>
    <ApplicationDisplayVersion>0.7.0</ApplicationDisplayVersion>
    <ApplicationVersion>8</ApplicationVersion>
    <AndroidPackageFormats>apk</AndroidPackageFormats>
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
    <RuntimeIdentifiers>android-arm64</RuntimeIdentifiers>
  </PropertyGroup>
  <ItemGroup><Compile Remove="tests/**/*.cs" /></ItemGroup>
</Project>
